initial_registration:
  input_file:         '/projects/net_contrast_classification/contrast_phase/Registration/registration_pairs.csv' #test2_data_pairs.xlsx' # train_data_pairs_sorted.xlsx' #
  output_folder:      '/mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/contrast_registrated' #test/' #
  output_folder_T0:   'T0_transform_parameters'
  output_file_param:  'T0_params.txt'
  folder_to_change:   'contrast_registrated'
  new_folder:         'contrast_registrated/liver_train' #liver_train' # liver_test
  fixed_col:          'fixed_liver_seg'
  moving_col:         'moving_liver_seg'
  subject_col:        'SubjectKeyRadiology'
  scan_dates:         'ExamDate'
  save_scans:         False
  radius_to_dilate:   10
  workers:            10
  mode:               local         # or "slurm"  for Dask-Jobqueue
  memory:             8GB


rigid_registration:
  input_file:         '/projects/net_contrast_classification/contrast_phase/Registration/registration_pairs.csv' # test2_data_pairs.xlsx' #test1_data_pairs.xlsx'       
  output_folder:      '/mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/contrast_registrated' # test/' # 
  output_folder_T1:   'T1_transform_parameters'
  input_file_param:   'T0_params.txt'
  output_file_param:  'T1_params.txt'
  folder_to_change:   'contrast_registrated'
  new_folder:         'contrast_registrated/liver_train' # liver_train' # liver_test'
  fix_img_col:        'fixed_image'
  mov_img_col:        'moving_image'
  fix_liv_col:        'fixed_organs'
  mov_liv_col:        'moving_organs'
  fix_tum_col:        'fixed_lesion_seg'
  mov_tum_col:        'moving_lesion_seg'
  subject_col:        'SubjectKeyRadiology'
  scan_dates:         'ExamDate'
  save_scans:         True
  is_test_data:       True
  radius:             5
  workers:            10 #20
  mode:               local         # or "slurm"  for Dask-Jobqueue
  memory:             8GB